### ISSUE TITLE
Split out climate change section to separate page

### ISSUE THREAD

**Issue by Mikanebu** [datahq/awesome-data#18]
We want to have a separate page for climate change.

## Acceptance criteria

* [x] climate change is accessible on https://datahub.io/awesome/climate-change

## Tasks

* [x] create `climate-change.md` page and add `title` and `description` into front matters and move content.
* [x] add link to the main page.

**Comment by Mikanebu** [comment]
FIXED, now climate change page is a separate page on https://datahub.io/awesome/climate-change
