### ISSUE TITLE
Create "Economic Data" section/page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/awesome-data#24]
As a User who's interested in "Economic data", I want to have one page that consolidates and describes all related datasets from DataHub so I can easily and pleasantly find datasets for my use.

As the DataHub team, we want to create "Economic data" page so we can attract traffic via search engines and provide great content for our users.

## Acceptance criteria

* [x] a thoroughly reviewed page about available "Economic data" on DataHub at `/awesome/economic-data`

## Tasks

* [x] draft a structure of the page
* [x] write an introduction for the page
* [x] go through the list of "core" datasets and identify which ones can be in "economic data" theme
* [x] draft a content
* [x] get a review from the team
* [x] improve per reviews
* [x] publish!

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/awesome/economic-data
