### ISSUE TITLE
One awesome page per subject

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/awesome-data#25]
As a Developer, I want to have "awesome" pages per subject so we can promote our existing "core" datasets on the web.

As a User, I want to be able to find datasets by theme via search engines so I can arrive at datahub and find all I need in one place.

## Acceptance criteria

* [x] all "core" datasets have a theme
* [x] all themes have a page
* [x] all pages have a reviewed content

## Tasks

* [x] go through the list of "core" datasets and assign a theme for each of them
* [x] create a page for each theme
* [x] write an intro paragraph for each theme
  * [x] get reviewed
  * [x] improve
* [x] create short content for each theme and link to the datasets

## Analysis

Possible subjects:

* economic data: gdp, cpi, population, employment etc.
* environmental or climate data: global temparature, co2-ppm etc.
* geographic data: country list, country codes, airport codes
* reference data: country list, all various codes (language codes etc)
* stock market data: finance-vix, s-and-p-500, nasdaq etc.
* medicine data ? e.g., we have pharmaceutical-drug-spending and genome-sequencing-costs

**Comment by anuveyatsu** [comment]
@akariv WDYT about subjects in the analysis section of the description?

**Comment by anuveyatsu** [comment]
Mostly FIXED

Not covered datasets:

- https://datahub.io/core/cirp-survey-of-freshmen (struggling to identify the subject)
- https://datahub.io/core/population-global-historical (struggling to identify the subject)
- https://datahub.io/core/membership-to-copyright-treaties (struggling to identify the subject)
- https://datahub.io/core/genome-sequencing-costs (healthcare data ?)
- https://datahub.io/core/pharmaceutical-drug-spending (healthcare data ?)

Datasets that could be in economic data as well as in stock market data:

- https://datahub.io/core/gold-prices
- https://datahub.io/core/oil-prices

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/awesome
