### ISSUE TITLE
Re-boot home page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/awesome-data#27]
As a User, I want the homepage to contain just a table of contents so that:
  * I can easily and quickly select a topic of my interest and go to the specific page without scrolling and reading other topics.
  * it is less confusing and simple to understand.

As a Developer, I want to have a straightforward structure of the awesome pages so that it is quicker and easier to add new pages. E.g., there is only one way to do it: I create a MD file and link to it from homepage.

## Acceptance criteria

* [x] homepage is a simple table of content that links to specific awesome pages
* [x] all existing content on the homepage is moved to its own pages

## Tasks

* [x] move machine learning, inflation, property prices, wealth income and inequality sections to their own pages
* [x] remove all extra content from homepage
* [x] create hand made table of content

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/awesome
